#!/usr/bin/env bash
#
# @category Update JSRoll RIA (Rich Internet Application) / SPA (Single-page Application) javascript framework
# @author Андрей Новиков <andrey@novikov.be>
# @data 07/12/2015
#

echo "jsroll post-update ..."
mkdir -p ./public/js/

if [ ! -f ./public/js/jsroll.min.js ]; then
    ln -s ./../../vendor/bermud-ru/jsroll/build/jsroll.min.js ./public/js/jsroll.min.js
fi

