#!/usr/bin/env bash
#
# @category Installation nginx with TLS 1.3 (CentOS 7.x, 8.x)
# @author Андрей Новиков <andrey@novikov.be>
# @data 07/12/2015
#

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "jsroll post-update ..."
mkdir -p ./public/js/

if [ ! -f ./public/js/jsroll.min.js ]; then
    ln -s ./../../vendor/bermud-ru/jsroll/build/jsroll.min.js ./public/js/jsroll.min.js
fi

