#!/bin/sh

echo "Post-install ..."
mkdir -p ./public/js/
#cp ./vendor/bermud-ru/jsroll/build/jsroll.min.js ./public/js/
ln ./vendor/bermud-ru/jsroll/build/jsroll.min.js ./public/js/jsroll.min.js
read -p 'R u want install examples[Y/n]: ' answer
case "${answer}" in
    [yY]|[yY][eE][sS])
        echo "Examples for RIA/SPA JSRoll"
        mkdir -p ./public/js/jsroll
        cp -R ./vendor/bermud-ru/jsroll/examples/* ./public/js/jsroll
        ;;
esac